again

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -43,11 +43,22 @@ jobs:
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1
 
-      - name: build docker image,push
+      # - name: build docker image,push
+      #   run: |
+      #    docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+      #    docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+      #    echo ":: set_output name = image :: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+
+      - name: Build & Push Docker Image
         run: |
+         if [[ -z "$ECR_REGISTRY" || -z "$ECR_REPOSITORY" || -z "$IMAGE_TAG" ]]; then
+          echo "ERROR: One or more required variables (ECR_REGISTRY, ECR_REPOSITORY, IMAGE_TAG) are missing!"
+          exit 1
+         fi
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-         echo ":: set_output name = image :: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+         echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
+
 
 
 
